jobs:
  - name: sampleNod_runCI      
    type: runCI             
      
  - name: myRelease
    type: release
    steps:
      - IN: myVersion  
      - IN: sampleNod_runCI
      - TASK: managed                      
        bump: minor  
